project_id = "msratyvmnuvozuthgkmi"

[api]
enabled = true

[db]
major_version = 17

[functions.tally-map-start]
verify_jwt = false

[functions.tally-map-status]
verify_jwt = false

[functions.user-credits]
verify_jwt = false

[functions.book-build-start]
verify_jwt = false

[functions.book-build-status]
verify_jwt = false
